version: '3.8'
services:
  app:
    image: condhub
    container_name: condhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "sleep infinity"

networks:
  default: