version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: condhub
    container_name: condhub
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/JG/Documents/BACKUP_OLD_PC/JG/PROG/condhub/src:/app/src/
      - C:/Users/JG/Documents/BACKUP_OLD_PC/JG/PROG/condhub/dist:/app/dist/
      - C:/Users/JG/Documents/BACKUP_OLD_PC/JG/PROG/condhub/node_modules:/app/node_modules/
    command: bash -c "chmod +x bash.sh && ./bash.sh"