version: '3.8'
services:
  app:
    image: condhub
    container_name: condhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    volumes:
      - .:/usr/src/app
