# Use an official Node runtime as the base image
FROM node:20.15.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY tsconfig.json ./tsconfig.json
COPY package.json ./package.json
COPY nodemon.json ./nodemon.json

# Install npm dependencies
RUN npm install

# Install TypeScript globally
RUN npm install -g typescript@4.5.4

RUN npm uninstall @types/lodash
RUN npm install @types/lodash@4.17.5

# Install nodemon globally for development
RUN npm install -g nodemon

COPY bash.sh ./bash.sh

EXPOSE 8080
EXPOSE 5432