# Use an official Node runtime as the base image
FROM node:20.15.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY tsconfig.json ./tsconfig.json
COPY package.json ./package.json
COPY nodemon.json ./nodemon.json

# Install npm dependencies
RUN npm install

# Install TypeScript globally
RUN npm install -g typescript@4.5.4

RUN npm uninstall @types/lodash
RUN npm install @types/lodash@4.17.5
RUN npm install -g nodemon

# Install nodemon globally (assuming it's needed for your development server)

EXPOSE 8000

# Copy the rest of the application code

# Expose the port your app runs on

# Command to run your app using nodemon
#CMD ["npm","start"]
