version: '3.8'
services:
  app:
    image: condhub
    container_name: condhub
    ports:
      - "8000:8000"
    
    volumes:
      - ./src/:/app/src/
      - ./dist/:/app/dist/
      - ./node_modules/:/app/node_modules/

    command: "npm install && npm run dev"
